# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-da16d8d2-2014-4364-a932-29c1957e3b6a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-da16d8d2-2014-4364-a932-29c1957e3b6a".device = "/dev/disk/by-uuid/da16d8d2-2014-4364-a932-29c1957e3b6a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/1501-5E49";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-95dc154d-a51d-4265-962c-8abe5f563e56"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
